version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./fonts:/tmp/fonts
    deploy:
      resources:
        limits:
          cpus: "0.3"

volumes:
  fonts:
